### ISSUE TITLE
Missing supported additional bundle kinds

### ISSUE THREAD

**Issue by joelanford** [operator-framework/olm-docs#119]
https://olm.operatorframework.io/docs/tasks/creating-operator-manifests/#packaging-additional-objects-alongside-an-operator

The full list of supported kinds is encoded here: https://github.com/operator-framework/operator-registry/blob/92a0d745d8eaf7c6442120c44dd06512cf0f9f7a/pkg/lib/bundle/supported_resources.go#L4-L19

**Comment by jmrodri** [comment]
So basically we just need to add the missing items from the `supported_resources.go` into the packaging-additional-objects-alongside-an-operator document. That makes sense.

**Comment by timflannagan** [comment]
Daniel addressed this in the latest commit (https://github.com/operator-framework/olm-docs/commit/337d93dd5cec1a2e0046c9e66d78cdce05683673).
