### ISSUE TITLE
QuickStart guide to install etcd operator cannot complete

### ISSUE THREAD

**Issue by vincent-pli** [operator-framework/olm-docs#241]
I try `olm` with k8s version v1.24.0, then follow the guide to create `sub` for `etcd` operator, not work...
the root cause is since v1.22.0 the `apiextensions.k8s.io/v1beta1` has been stop to serve, but the `crd` for `etcd` is still `apiextensions.k8s.io/v1beta1` rather than `apiextensions.k8s.io/v1`

I noticed there is some annotation in `csv` of `etcd` operator like this:
```
uses removed APIs in 1.22 and will not work on K8S clusters 1.22+.
```

but it just `annotation` no checking, and I get something like this:
```
root@bosoms1:~# kubectl get csv
NAME                  DISPLAY   VERSION   REPLACES              PHASE
etcdoperator.v0.9.2   etcd      0.9.2     etcdoperator.v0.9.0   Pending
etcdoperator.v0.9.4   etcd      0.9.4     etcdoperator.v0.9.2   Pending
```

**Comment by m1kola** [comment]
Thanks for reporting this. I created PR #276 to address this.
